### ISSUE TITLE
Jar file should contain all dependencies inside and be standalone app

### ISSUE THREAD

**Issue by yehorsyrin** [chilya-coder/TaskManager#2]
Please, update pom.xml and provide a command for building application. Jar file should contain all dependencies inside. Also, you should provide a link to google drive folder with a jar file and bat file that runs the app.

**Comment by chilya-coder** [comment]
Commit: e746e81
https://drive.google.com/drive/folders/1jIrSOAPf7vyOZBIJ8SIUhGR8D7ZcGGG6?usp=sharing
